### ISSUE TITLE
Minus Pressure Value

### ISSUE THREAD

**Issue by taketomatsunaga** [m5stack/UNIT_ENV#2]
The value of the pressure from is '-343349Pa'.
It is an absolute pressure, so it is supposed to be around 1013hPa and never be minus value?

Code: https://github.com/m5stack/UNIT_ENV/blob/master/examples/UNIT_ENV_III/UNIT_ENV_III.ino

Thank you for your help in advance.

**Comment by taketomatsunaga** [comment]
Could you help me? @Tinyu-Zhao

**Comment by Tinyu-Zhao** [comment]
Which host are you using, is the Unit ENV version I or II or III, and are you connected to the correct port?

**Comment by taketomatsunaga** [comment]
@Tinyu-Zhao 
Thank you for your support.
But I am sorry. I just reconnected the uart connector and it worked.

**Comment by Tinyu-Zhao** [comment]
It's okay, no problem is good
